#!/bin/bash -i

# Commands
python() {
    python3.8 "${@}"
}

# Color tables
cyan() {
    echo -e "\033[0;36m${@}"
}

yellow() {
    echo -e "\033[0;33m${@}"
}

white(){
    echo -e "\033[0;37m${@}"
}

# Constants
base_dir=$(dirname "${0}")
cmd=${1}

# Main

if [ "${1}" == "change" ]; then
    if [ "${2}" == 'url' ]; then
        python ${base_dir}/script/modules/side_configure/master.py change --target=url --path=${base_dir}/tests/**/*.side --url=${3}
    fi
    if [ "${2}" == 'user' ]; then
        python ${base_dir}/script/modules/side_configure/master.py change --target=user --path=${base_dir}/tests/**/*.side --user=${3} --password=${4}
    fi
fi

echo -e "\033[0m"
